<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'GitHubAccountCustomField' => 'src/customfields/GitHubAccountCustomField.php',
    'MediaWikiUserpageCustomField' => 'src/customfields/MediaWikiUserpageCustomField.php',
    'PhabricatorMediaWikiAuthProvider' => 'src/oauth/PhabricatorMediaWikiAuthProvider.php',
    'PhutilMediaWikiAuthAdapter' => 'src/oauth/PhutilMediaWikiAuthAdapter.php',
    'SecurityPolicyEnforcerAction' => 'src/policy/SecurityPolicyEnforcerAction.php',
    'WMFEscalateTaskController' => 'src/policy/WMFLockTaskController.php',
    'WMFEscalateTaskEventListener' => 'src/policy/WMFLockTaskEventListener.php',
    'WMFExtensionsApplication' => 'src/policy/TestWikiExtensionsApplication.php',
    'WMFSecurityPolicy' => 'src/policy/WMFSecurityPolicy.php',
    'WMFSubscribersPolicyRule' => 'src/policy/WMFSubscribersPolicyRule.php',
  ),
  'function' => array(),
  'xmap' => array(
    'GitHubAccountCustomField' => 'PhabricatorUserCustomField',
    'MediaWikiUserpageCustomField' => 'PhabricatorUserCustomField',
    'PhabricatorMediaWikiAuthProvider' => 'PhabricatorOAuth2AuthProvider',
    'PhutilMediaWikiAuthAdapter' => 'PhutilOAuthAuthAdapter',
    'SecurityPolicyEnforcerAction' => 'HeraldAction',
    'WMFEscalateTaskController' => 'PhabricatorController',
    'WMFEscalateTaskEventListener' => 'PhabricatorEventListener',
    'WMFExtensionsApplication' => 'PhabricatorApplication',
    'WMFSubscribersPolicyRule' => 'PhabricatorPolicyRule',
  ),
));
