<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'CustomLoginHandler' => 'src/other/CustomLoginHandler.php',
    'GitHubAccountCustomField' => 'src/customfields/GitHubAccountCustomField.php',
    'MediaWikiUserpageCustomField' => 'src/customfields/MediaWikiUserpageCustomField.php',
    'PhabricatorMediaWikiAuthProvider' => 'src/oauth/PhabricatorMediaWikiAuthProvider.php',
    'PhutilMediaWikiAuthAdapter' => 'src/oauth/PhutilMediaWikiAuthAdapter.php',
  ),
  'function' => array(),
  'xmap' => array(
    'CustomLoginHandler' => 'PhabricatorAuthLoginHandler',
    'GitHubAccountCustomField' => 'PhabricatorUserCustomField',
    'MediaWikiUserpageCustomField' => 'PhabricatorUserCustomField',
    'PhabricatorMediaWikiAuthProvider' => 'PhabricatorOAuth1AuthProvider',
    'PhutilMediaWikiAuthAdapter' => 'PhutilOAuth1AuthAdapter',
  ),
));
